### ISSUE TITLE
Expiration time signed url

### ISSUE THREAD

**Issue by myckel** [carrierwaveuploader/carrierwave-google-storage#38]
I am trying to configure the expiration time, I have tried with several values but always the expiration time of the url is 5 minutes, I have the following configuration of carrierwave

```
CarrierWave.configure do |config|

  config.storage                             = :gcloud
  config.gcloud_bucket                       = ENV['GCLOUD_BUCKET']
  config.gcloud_bucket_is_public             = false
  config.gcloud_authenticated_url_expiration = 604800

  config.gcloud_attributes = {
    expires: 604800
  }

   config.gcloud_credentials = {
    gcloud_project: ENV['GCLOUD_PROJECT_ID'],
    gcloud_keyfile: ENV['GCLOUD_KEY_FILE']
  }
end

**Comment by santigibo** [comment]
Did you found a way to solve this? I'm having the same issue with this and I can't get to change the expiration time for the URL. It would be really helpful if maybe you have some information about this issue.. Thanks :D

**Comment by matthewford** [comment]
Also running into this issue

**Comment by sunil-edcast** [comment]
I am also facing the same issue with GCP only.
